main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView

from .views import markdown_uploader

admin.site.site_header = '七友•管理'
admin.site.index_title = '后台主页'
admin.site.site_title = '管理后台'

favicon_view = RedirectView.as_view(url=static_url('favicon.ico'), permanent=True)
robots_view = RedirectView.as_view(url=static_url('robots.txt'), permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    re_path(r'^robots\.txt$', robots_view),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from . import apis

app_name = 'pages'
urlpatterns = [
    path('', views.view_index, name='index'),
    path('article/', views.view_list, name='list'),
    path('article/<int:article_id>', views.view_detail, name='detail'),
    path('copyright/', views.view_copyright, name='copyright'),
    path('about/', views.view_about, name='about'),
    path('message/', views.view_message, name='message'),
    path('search/', views.view_search, name='search'),
    path('analysis/article/', apis.api_article_analysis, name='article_analysis'),
    path('generate-captcha/', apis.api_generate_captcha, name='generate_captcha'),
    path('leave-message/', apis.api_leave_message, name='leave_message'),
]

pages/templates/article/list.html
{% extends "base-layout.html" %}
{% load static %}

{% block title %}博文列表 - {{ block.super }}{% endblock %}

{% block head_css %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/bootstrap-select/1.13.10/css/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content_left %}
    <ul class="list-group blog-list-panel">
        {% for article in article_list %}
            <li class="list-group-item">
                <h4 class="list-group-item-heading">
                    <a href="{% url 'pages:detail' article.id %}">{{ article.title }}</a>
                    {% if user.is_authenticated %}
                    <span class="ico-btn-edit">
                        <a href="{% url 'admin:pages_article_change' article.id %}" title="编辑">
                            <i class="far fa-edit"></i>
                        </a>
                    </span>
                    {% endif %}
                </h4>
                <p class="list-group-item-text">{{ article.abstract }}</p>
                <div class="list-group-item-footing">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            {% for tag in article.tags.all %}
                                <a href="{% url 'pages:search' %}?tag={{ tag.id }}" class="tag-item">
                                    <span class="tag-wrapper"><i class="fas fa-tag"></i>{{ tag.name }}</span>
                                </a>
                            {% empty %}
                                <span class="text-muted">没有添加标签</span>
                            {% endfor %}
                        </div>
                        <div class="col-xs-12 col-sm-6 text-right">
                            <span class="text-muted">{{ article.upate_time }}</span>
                        </div>
                    </div>
                </div>
            </li>
        {% empty %}
            <li class="list-group-item">
                <p class="list-group-item-text">作者懒到家了，没有写文章</p>
            </li>
        {% endfor %}
    </ul>
    <div class="blog-list-pagination">
        <nav aria-label="blog-list-pagination">
            <ul class="pager">
                {% if article_list.has_previous %}
                    <li class="previous">
                        <a href="?page={{ article_list.previous_page_number }}">
                            <span aria-hidden="true">&larr;</span> 上一页
                        </a>
                    </li>
                {% else %}
                    <li class="previous disabled">
                        <a href="javascript:;">
                            <span aria-hidden="true">&larr;</span> 上一页
                        </a>
                    </li>
                {% endif %}
                <li class="current">
                    <span>
                        <select data-current="{{ article_list.number }}" data-max="{{ article_list.paginator.num_pages }}" class="selectpicker" data-live-search="true" data-width="fit">
                            <option>{{ article_list.number }}</option>
                        </select> /
                        <strong>{{ article_list.paginator.num_pages }}</strong>
                    </span>
                </li>
                {% if article_list.has_next %}
                    <li class="next">
                        <a href="?page={{ article_list.paginator.num_pages }}">
                            下一页 <span aria-hidden="true">&rarr;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="next disabled">
                        <a href="javascript:;">
                            下一页 <span aria-hidden="true">&rarr;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

{% block content_right %}
    <div class="panel panel-default tags-panel">
        <div class="panel-heading">
            <h3 class="panel-title">标签</h3>
        </div>
        <div class="panel-body">
            {% for tag in tag_list %}
                <a href="{% url 'pages:search' %}?tag={{ tag.id }}" class="tag-item">
                    <span class="tag-text">{{ tag.name }}</span>
                    <span class="badge">{{ tag.articles.count }}</span>
                </a>
            {% empty %}
                <span class="tag-text">测试</span>
            {% endfor %}
      </div>
    </div>
{% endblock %}

{% block footer_js %}
    <script src="{% static 'libs/bootstrap-select/1.13.10/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'libs/bootstrap-select/1.13.10/js/i18n/defaults-zh_CN.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var $sel = $('select.selectpicker');
            $sel.empty();
            var current = parseInt($sel.attr('data-current')),
                max = parseInt($sel.attr('data-max'));
            for (var i = 1; i <= max; i++) {
                $sel.append([
                    '<option>', i, '</option>'
                ].join(''));
            }
            $sel.val(current);
            $sel.on('changed.bs.select', function(event, clickedIndex, isSelected, previousValue) {
                if(isSelected) {
                    var new_page = $(this).find('option:eq(' + clickedIndex + ')').text().trim();
                    window.location.href = '?page=' + new_page;
                }
            });
        });
    </script>
{% endblock %}

pages/templates/article/search.html
{% extends "base-layout.html" %}
{% load static %}

{% block title %}博文搜索 - {{ block.super }}{% endblock %}

{% block head_css %}
    {{ block.super }}
    <link href="{% static 'css/search.css' %}" rel="stylesheet" type="text/css" />
    <style type="text/css">
        #page-main {
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-md-12 text-center">
            <div id="page-main">
                搜索功能-页面-待开发中
            </div>
        </div>
    </div>
{% endblock %}