main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView

from .views import markdown_uploader

admin.site.site_header = '七友•管理'
admin.site.index_title = '后台主页'
admin.site.site_title = '管理后台'

favicon_view = RedirectView.as_view(url=static_url('favicon.ico'), permanent=True)
robots_view = RedirectView.as_view(url=static_url('robots.txt'), permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    re_path(r'^robots\.txt$', robots_view),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from . import apis

app_name = 'pages'
urlpatterns = [
    path('', views.view_index, name='index'),
    path('article/', views.view_list, name='list'),
    path('article/<int:article_id>', views.view_detail, name='detail'),
    path('copyright/', views.view_copyright, name='copyright'),
    path('about/', views.view_about, name='about'),
    path('message/', views.view_message, name='message'),
    path('search/', views.view_search, name='search'),
    path('analysis/article/', apis.api_article_analysis, name='article_analysis'),
    path('generate-captcha/', apis.api_generate_captcha, name='generate_captcha'),
    path('leave-message/', apis.api_leave_message, name='leave_message'),
]

pages/templates/me/about.html
{% extends "base-layout.html" %}

{% block title %}关于[{{ CFG.SITE_INFO.WHOAMI }}] - {{ block.super }}{% endblock %}

{% block head_css %}
    {{ block.super }}
    <style type="text/css">
        #page-main {
            min-height: 100px;
            margin: 0 auto;
            max-width: 38em;
            text-align: left;
        }
        #page-main dd {
            text-indent: 2em;
            /*text-decoration: underline dotted #fa1;*/
            text-shadow: #a1b3f3 1px 2px 8px;
        }
        #page-main dd + dt {
            margin-top: 0.39em;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-md-12 text-center">
            <div id="page-main">
                <dl>
                    <dt>昵称:</dt>
                    <dd>七友！</dd>
                    <dt>网络用户名:</dt>
                    <dd>qiooyou</dd>
                    <dt>名称释意:</dt>
                    <dd>七个小朋友</dd>
                    <dt>说明:</dt>
                    <dd>网络上，<strong>qiooyou</strong>一般是我，但不全是， :)</dd>
                    <dt>
                        Github
                    </dt>
                    <dd>
                        <a href="https://github.com/qiooyou/" target="_blank">qiooyou</a>
                    </dd>
                    <dt>最喜欢(用着最有感觉)的编程语言:</dt>
                    <dd>
                        <a href="https://www.python.org/">Python</a>
                    </dd>
                    <dt>最不喜欢使用的编程语言:</dt>
                    <dd>
                        <span style="text-decoration: line-through">Java</span>
                    </dd>
                    <dt>还会点儿啥:</dt>
                    <dd>C#、PHP、Node.JS ~</dd>
                    <dt>最喜欢(常用)使用的操作系统:</dt>
                    <dd>
                        <a href="https://www.ubuntu.com/" target="_blank">Ubuntu</a>
                    </dd>
                    <dt>最不喜欢使用的操作系统:</dt>
                    <dd>
                        <span style="text-decoration: line-through">CentOS</span>
                    </dd>
                    <dt>特别说明:</dt>
                    <dd>
                        <a href="http://blog.gsw945.com/">博客</a> 内容，部分参考自 <a href="https://stackoverflow.com/" target="_blank">Stack Overflow</a>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/me/copyright.html
{% extends "base-layout.html" %}

{% block title %}版权声明 - {{ block.super }}{% endblock %}

{% block head_css %}
    {{ block.super }}
    <style type="text/css">
        #page-main {
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-md-12 text-center">
            <div id="page-main">
                页面待开发中
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/me/message.html
{% extends "base-layout.html" %}

{% block title %}给[{{ CFG.SITE_INFO.WHOAMI }}]留言 - {{ block.super }}{% endblock %}

{% block head_css %}
    {{ block.super }}
    <style type="text/css">
        #page-main {
        }
        .title-divider {
            margin-right: -20px;
            margin-left: -20px;
        }
        @media(min-width: 768px) {
            .title-divider {
                margin-left: 0;
            }
        }
        #txt-content {
            resize: vertical;
        }
        #btn-submit {
            margin-right: 2em;
        }
        .form-line-wrapper {
            display: block;
            width: 100%;
            height: 34px;
            padding: 6px 6px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border-radius: 4px;
        }
        .captcha-img {
            cursor: pointer;
            vertical-align: top;
        }
        #txt-captcha {
            margin-left: 0.8em;
            padding: 0.1em 0.5em;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class=" col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            <div class="col-sm-offset-2 col-sm-10">
                <h3>给[{{ CFG.SITE_INFO.WHOAMI }}]留言</h3>
            </div>
            <div class="col-sm-12">
                <hr class="title-divider" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class=" col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            <div class="form-horizontal">
                <div class="form-group">
                    <label for="txt-email" class="col-sm-2 control-label">邮箱</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="txt-email" placeholder="邮箱">
                    </div>
                </div>
                <div class="form-group">
                    <label for="txt-content" class="col-sm-2 control-label">内容</label>
                    <div class="col-sm-10">
                        <textarea rows="5" class="form-control" id="txt-content"  placeholder="留言内容"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">回复</label>
                    <div class="col-sm-10">
                        <label class="radio-inline">
                            <input type="radio" name="rdo-reply" id="rdo-reply-yes" value="yes"> 期待
                        </label>
                        <label class="radio-inline">
                            <input checked="checked" type="radio" name="rdo-reply" id="rdo-reply-no" value="no"> 不必
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">验证</label>
                    <div class="col-sm-10">
                        <div class="form-line-wrapper">
                            <img class="captcha-img" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="验证码" title="不区分大小写, 点击刷新" />
                            <input type="text" id="txt-captcha" placeholder="验证码" size="12" />
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 text-right">
                        <button type="button" id="btn-submit" class="btn btn-default">提 交</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
    <script type="text/javascript">
        // 模板变量
        GLOGAL.GENERATE_CAPTCHA_URL = "{% url 'pages:generate_captcha' %}";
        GLOGAL.LEAVE_MESSAGE_URL = "{% url 'pages:leave_message' %}";
    </script>
    <script type="text/javascript">
        /**
         * 刷新验证码
         */
        function refresh_captcha() {
            $.ajax({
                url: GLOGAL.GENERATE_CAPTCHA_URL,
                type: 'POST',
                data: {},
                dataType: 'json'
            }).done(function(resp) {
                // console.log(resp);
                if(resp.error == 0)  {
                    $('.captcha-img').attr('src', resp.data);
                }
                else {
                    alert(resp.desc);
                }
            }).fail(function(err) {
                console.error(err);
            });
        }

        /**
         * 提交留言
         */
        function submit_message(email, content, reply, captcha) {
            $.ajax({
                url: GLOGAL.LEAVE_MESSAGE_URL,
                type: 'POST',
                data: {
                    email: email,
                    content: content,
                    reply: reply,
                    captcha: captcha
                },
                dataType: 'json'
            }).done(function(resp) {
                // console.log(resp);
                alert(resp.desc);
                if(resp.error == 0)  {
                    window.location.href = window.location.href;
                }

            }).fail(function(err) {
                console.error(err);
            });
        }

        $(document).ready(function() {
            refresh_captcha();
            $('.captcha-img').on('click', refresh_captcha);
            $('#btn-submit').on('click', function() {
                var email = $('#txt-email').val(),
                    content = $('#txt-content').val(),
                    reply = $('#rdo-reply-yes').prop('checked'),
                    captcha = $('#txt-captcha').val();
                submit_message(email, content, reply, captcha);
            });
        });
    </script>
{% endblock %}