main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView

from .views import markdown_uploader

admin.site.site_header = '七友•管理'
admin.site.index_title = '后台主页'
admin.site.site_title = '管理后台'

favicon_view = RedirectView.as_view(url=static_url('favicon.ico'), permanent=True)
robots_view = RedirectView.as_view(url=static_url('robots.txt'), permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    re_path(r'^robots\.txt$', robots_view),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from . import apis

app_name = 'pages'
urlpatterns = [
    path('', views.view_index, name='index'),
    path('article/', views.view_list, name='list'),
    path('article/<int:article_id>', views.view_detail, name='detail'),
    path('copyright/', views.view_copyright, name='copyright'),
    path('about/', views.view_about, name='about'),
    path('message/', views.view_message, name='message'),
    path('search/', views.view_search, name='search'),
    path('analysis/article/', apis.api_article_analysis, name='article_analysis'),
    path('generate-captcha/', apis.api_generate_captcha, name='generate_captcha'),
    path('leave-message/', apis.api_leave_message, name='leave_message'),
]

pages/templates/widgets/layout-footer.html
<div class="row page-footer">
    <p class="text-center">
        <strong>
            <a href="{% url 'pages:about' %}">{{ CFG.SITE_INFO.COPYRIGHT|default:CFG.SITE_INFO.WHOAMI }}</a>
            © {% now "Y" %}
        </strong>
        <small>保留所有权利</small>
        <a class="github-icon" href="https://github.com/gsw945/myblog">
            <i class="fab fa-github-square"></i>
        </a>
    </p>
    <p class="text-center">
        <a href="http://www.miitbeian.gov.cn/" target="_blank">{{ CFG.SITE_INFO.ICP }}</a>
    </p>
</div>

pages/templates/widgets/loading-html.html
<!-- https://loading.io/css/ -->
<div class="loading-wrapper">
    <div class="lds-ripple">
        <div></div>
        <div></div>
    </div>
    <div class="loading-text-wrapper">
        <span class="loading-text">{{ loading_text }}</span>
    </div>
</div>

pages/templates/widgets/loading-style.html
<style type="text/css">
.lds-ripple {
    display: inline-block;
    position: relative;
    width: 64px;
    height: 64px;
}
.lds-ripple div {
    position: absolute;
    border: 4px solid #0035ff;
    opacity: 1;
    border-radius: 50%;
    animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(2) {
    animation-delay: -0.5s;
}
@keyframes lds-ripple {
    0% {
        top: 28px;
        left: 28px;
        width: 0;
        height: 0;
        opacity: 1;
    }
    100% {
        top: -1px;
        left: -1px;
        width: 58px;
        height: 58px;
        opacity: 0;
    }
}
.loading-wrapper {
    text-align: center;
    min-height: 50vh;
    padding: 8vh 0;
}

.loading-text-wrapper {
    margin-top: -0.8em;
}

.loading-text {
    /*
    position: absolute;
    top: 20px;
    width: 100%;
    left: -2px;
    */
    /* https://css-tricks.com/almanac/properties/a/animation/#article-header-id-7 */
    -webkit-animation: flash 0.8s infinite;
    -moz-animation:    flash 0.8s infinite;
    -o-animation:      flash 0.8s infinite;
    animation:         flash 0.8s infinite;
}

@-webkit-keyframes flash {
  0%   { opacity: 0.1; }
  100% { opacity: 0.9; }
}
@-moz-keyframes flash {
  0%   { opacity: 0.1; }
  100% { opacity: 0.9; }
}
@-o-keyframes flash {
  0%   { opacity: 0.1; }
  100% { opacity: 0.9; }
}
@keyframes flash {
  0%   { opacity: 0.1; }
  100% { opacity: 0.9; }
}
</style>

pages/templates/widgets/top-nav.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pages:index' %}">{{ CFG.SITE_INFO.BRAND|safe }}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li data-page-view="admin:pages_article_add"><a href="{% url 'admin:pages_article_add' %}">去写博客</a></li>
                {% endif %}
                <li data-page-view="pages:list"><a href="{% url 'pages:list' %}"><strong>博文列表</strong></a></li>
                <!--
                <li data-page-view="pages:copyright"><a href="{% url 'pages:copyright' %}">版权声明</a></li>
                -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        点我 <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li data-page-view="pages:about"><a href="{% url 'pages:about' %}">关于我</a></li>
                        <li role="separator" class="divider"></li>
                        <li data-page-view="pages:message"><a href="{% url 'pages:message' %}">给我留言</a></li>
                    </ul>
                </li>
                <li class="top-nav-search">
                    <!-- <input type="text" name="txt-search" placeholder="search" /> -->
                    <form action="{% url 'pages:search' %}" id="header-search" class="navbar-form" role="search">
                        <div class="form-group">
                            <div class="input-group-container header-search">
                                <span class="input-group-container-addon">
                                    <span class="glyphicon glyphicon-search"></span>
                                </span>
                                <input type="text" class="form-control" placeholder="回车搜索" name="query" value="{{ request.GET.query }}" />
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>